// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nilpqhkxoywynccmupqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pbHBxaGt4b3l3eW5jY211cHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDU0MDcsImV4cCI6MjA3MDU4MTQwN30.7ixoqUvqJcco4s1m-Hs2937Exe61kDRJTNNE1BCTS_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});